services:
  nginx:
    image: nginx:1.15-alpine
    restart: unless-stopped
    container_name: nginx_test
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    networks:
      - test_intranet
    ports:
      - 80:80
      - 443:443

  certbot:
    image: certbot/certbot
    container_name: certbot_test
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    networks:
      - test_intranet
    command: certonly --webroot -w /var/www/certbot -d api-test.projectlive.me --noninteractive --email vivekcharak004@gmail.com --agree-tos

  backend:
    build: .
    container_name: backend_test
    networks:
      - test_intranet

networks:
  test_intranet: